"""Exact unrestricted-codebook optimisation primitives."""

from sphere_encoding.exact.artifacts import (
    write_instance_artifacts,
    write_stage4_tables,
)
from sphere_encoding.exact.model import (
    ExactFeasibilityModel,
    StructuralLowerBound,
    build_exact_feasibility_model,
    canonicalise_hint_codes,
    deterministic_odd_cycle,
    model_proto_bytes,
    structural_lower_bound,
)
from sphere_encoding.exact.plan import (
    BaselineChoice,
    FrozenInputIdentity,
    InstancePlan,
    Stage4Plan,
    TargetPlan,
    derive_stage4_plan,
    equal_target_budget,
    load_stage3_baseline_rows,
    select_baseline_row,
    stage4_plan_payload,
    verify_frozen_input_identities,
)
from sphere_encoding.exact.run import (
    InstanceClassification,
    InstanceExecution,
    TargetExecution,
    classify_instance_executions,
    execute_instance_plan,
)
from sphere_encoding.exact.solver import (
    ExactSolveResult,
    ExactSolverStatus,
    StatusInterpretation,
    WitnessValidation,
    interpret_solver_status,
    recompute_edge_hamming,
    solve_exact_feasibility_model,
    validate_exact_witness,
)

__all__ = [
    "BaselineChoice",
    "ExactFeasibilityModel",
    "ExactSolveResult",
    "ExactSolverStatus",
    "FrozenInputIdentity",
    "InstanceClassification",
    "InstanceExecution",
    "InstancePlan",
    "Stage4Plan",
    "StatusInterpretation",
    "StructuralLowerBound",
    "TargetExecution",
    "TargetPlan",
    "WitnessValidation",
    "build_exact_feasibility_model",
    "canonicalise_hint_codes",
    "classify_instance_executions",
    "derive_stage4_plan",
    "deterministic_odd_cycle",
    "equal_target_budget",
    "execute_instance_plan",
    "interpret_solver_status",
    "load_stage3_baseline_rows",
    "model_proto_bytes",
    "recompute_edge_hamming",
    "select_baseline_row",
    "solve_exact_feasibility_model",
    "stage4_plan_payload",
    "structural_lower_bound",
    "validate_exact_witness",
    "verify_frozen_input_identities",
    "write_instance_artifacts",
    "write_stage4_tables",
]
