"""Deterministic scalable free-codebook search primitives."""

from sphere_encoding.heuristic.initialisation import (
    InitialisationError,
    InitialisationResult,
    derive_seed,
    load_stage3_baseline,
    load_stage4_witness,
    random_injective_initialisation,
    zero_pad_state,
)
from sphere_encoding.heuristic.moves import (
    MoveEvaluation,
    ReplacementMove,
    SwapMove,
    affected_edge_indices,
    apply_evaluated_move,
    apply_move,
    evaluate_move,
)
from sphere_encoding.heuristic.planning import (
    CODE_LENGTH_OFFSETS,
    GRAPH_ORDER,
    DirectStage4ExactPair,
    GraphPlanningRecord,
    NativeCodebookSource,
    PlannedInitialisation,
    PlanningError,
    Stage5InstancePlan,
    Stage5Plan,
    Stage5TargetPlan,
    build_stage5_plan,
    stage5_plan_payload,
)
from sphere_encoding.heuristic.schedule import (
    AcceptanceDecision,
    LinearTemperatureSchedule,
    ScheduleError,
    acceptance_decision,
)
from sphere_encoding.heuristic.scoring import (
    IncrementalScoringState,
    ScoringError,
    ThresholdScore,
    canonical_edges_array,
    score_codebook,
    score_edge_distances,
)
from sphere_encoding.heuristic.search import (
    SearchError,
    SearchKernelCheckpoint,
    SearchKernelConfig,
    SearchKernelResult,
    SearchStep,
    propose_move,
    run_search_kernel,
    search_edges_sha256,
    search_kernel_config_payload,
    search_kernel_config_sha256,
)
from sphere_encoding.heuristic.state import (
    SearchState,
    SearchStateError,
    codeword_id_to_row,
    codeword_rows_to_ids,
)
from sphere_encoding.heuristic.verification import (
    SearchVerificationReport,
    VerificationError,
    verify_search_result,
)

__all__ = [
    "CODE_LENGTH_OFFSETS",
    "GRAPH_ORDER",
    "AcceptanceDecision",
    "DirectStage4ExactPair",
    "GraphPlanningRecord",
    "IncrementalScoringState",
    "InitialisationError",
    "InitialisationResult",
    "LinearTemperatureSchedule",
    "MoveEvaluation",
    "NativeCodebookSource",
    "PlannedInitialisation",
    "PlanningError",
    "ReplacementMove",
    "ScheduleError",
    "ScoringError",
    "SearchError",
    "SearchKernelCheckpoint",
    "SearchKernelConfig",
    "SearchKernelResult",
    "SearchState",
    "SearchStateError",
    "SearchStep",
    "SearchVerificationReport",
    "Stage5InstancePlan",
    "Stage5Plan",
    "Stage5TargetPlan",
    "SwapMove",
    "ThresholdScore",
    "VerificationError",
    "acceptance_decision",
    "affected_edge_indices",
    "apply_evaluated_move",
    "apply_move",
    "build_stage5_plan",
    "canonical_edges_array",
    "codeword_id_to_row",
    "codeword_rows_to_ids",
    "derive_seed",
    "evaluate_move",
    "load_stage3_baseline",
    "load_stage4_witness",
    "propose_move",
    "random_injective_initialisation",
    "run_search_kernel",
    "score_codebook",
    "score_edge_distances",
    "search_edges_sha256",
    "search_kernel_config_payload",
    "search_kernel_config_sha256",
    "stage5_plan_payload",
    "verify_search_result",
    "zero_pad_state",
]
